spring:
  application:
    name: spring-ai-practical
  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_API_KEY:add-your-api-key-here} # https://platform.openai.com/api-keys
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
          temperature: ${OPENAI_TEMPERATURE:0.7}
          max-tokens: ${OPENAI_MAX_TOKENS:500}